name: Build and Release BeeperLite

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build Windows portable and installer
        run: npm run build-all
      
      - name: Upload Portable
        uses: actions/upload-artifact@v4
        with:
          name: BeeperLite-Portable
          path: dist/BeeperLite.Portable.*.exe
      
      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: BeeperLite-Setup
          path: dist/BeeperLite.Setup.*.exe
      
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/BeeperLite.Portable.*.exe
            dist/BeeperLite.Setup.*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
